services:
  dev-environment:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces/Checkmate # mount the workspace to /workspace
      - ../.git:/workspaces/Checkmate/.git
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: checkmate
      JUPYTER_TOKEN: easy
      TZ: Europe/Berlin
    tty: true
  test-build:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: checkmate-backend:latest
    # registry.wildwolfwuff.de/checkmate-backend
    ports:
      - 8001:8000
    env_file:
      - ./.env
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: checkmate
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  postgres_data: